import { QueryProvider } from "@/providers/query-client";
import localFont from "next/font/local";

const satoshi = localFont({
  src: "./satoshi.woff2",
});

import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${satoshi.className} antialiased`}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
